no sh

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -91,9 +91,13 @@ jobs:
       run: |          
         mkdir lineage      
         cd lineage
-        repo init -u https://github.com/LineageOS/android.git -b lineage-22.2
-        wget https://raw.githubusercontent.com/yu13140/Redmi8_Kernel_Patches/refs/heads/main/yuzkernel.sh
-        bash yuzkernel.sh
+        echo "======start repo sync======"
+        repo sync -c -j32 --no-clone-bundle
+        while [ $? = 1 ]; do
+           echo "======sync failed, re-sync again======"
+           sleep 3
+           repo sync -c -j32 --no-clone-bundle
+        done
         echo "======Ending Repo======"
         ls device
         ls device/xiaomi
